### ISSUE TITLE
Potential issue with 217b6fa - pipeline separated across several lines

### ISSUE THREAD

**Issue by yichizhang** [sharplet/dotfiles#1]
I changed the function name from `go` to `cdpj`

With version 217b6fa pipeline separated across several lines, I see some errors:

```
cdpj:14: parse error near `|'
cdpj:12: parse error in command substitution
```

With one liner version in b823cc1, it works

**Comment by sharplet** [comment]
Yeah looks like the way I'm using comments after (what's supposed to be) the escaped new line is completely wrong. I'll delete the doc comments and push up the fix, thanks!
